/*
BE VERY CAREFUL OF CHANGING THE PANEL NAMES IN MAIN PANEL
CARD LAYOUT USES THESE NAMES TO CALL THE PANEL
 */
package UI;

import custom.components.HotelListItemPanel;
import internal.HotelDesc;
import internal.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import verifyingTools.Verify;
import bridge.Helper;
import internal.DialogActionListener;
import java.awt.Dialog;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Sarthak
 */
public class MainForm extends javax.swing.JFrame implements MouseListener {//Mouse Listener for the mouse events in HotelListItemPanel

    User user;
    LoginForm loginScreen;
    HotelListItemPanel resultList[];
    private static final String STAR = "\u2605";
    private int numOfRooms;
    private int numOfGuest;
    private LocalDate checkIn;
    private LocalDate checkOut;
    private static long NUMBER_OF_FUTURE_YEARS=4;
    DialogActionListener dal;

    /**
     * Creates new form Main
     */

    public MainForm(User user, LoginForm l) {
        this.user = user;
        initComponents();
        startupCode();
        loginScreen = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        changePasswordDialog = new javax.swing.JDialog();
        changePasswordOkButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oldPasswordPF = new javax.swing.JPasswordField();
        confirmNewPasswordPF = new javax.swing.JPasswordField();
        newPasswordPF = new javax.swing.JPasswordField();
        modifyDateDialog = new javax.swing.JDialog();
        modifyDateDialogPanel1 = new custom.components.ModifyBookingDialogPanel();
        changeGuestRoomDialog = new javax.swing.JDialog();
        guestRoomDialogPanel2 = new custom.components.GuestRoomDialogPanel();
        sidebar = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        bookHotelsPanelButton = new javax.swing.JPanel();
        bookHotelsLabel = new javax.swing.JLabel();
        myBookingsPanelButton = new javax.swing.JPanel();
        myBookingsLabel = new javax.swing.JLabel();
        settingsPanelButton = new javax.swing.JPanel();
        myProfileLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        logoutLinkLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        bookPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priceSlider = new javax.swing.JSlider();
        locationComboBox = new javax.swing.JComboBox<>();
        roomPanel = new javax.swing.JPanel();
        roomScrollPane = new javax.swing.JScrollPane();
        roomListPanel = new javax.swing.JPanel();
        goButton = new javax.swing.JButton();
        titlePanelBook = new javax.swing.JPanel();
        priceSpinner = new javax.swing.JSpinner();
        titleLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        checkInDatePanel = new custom.components.DatePanel();
        checkOutDatePanel = new custom.components.DatePanel();
        guestRoomPanel1 = new custom.components.GuestRoomPanel();
        myProfilePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        fNameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        titlePanelSettings = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mobileTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pinCodeTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dobTF = new javax.swing.JTextField();
        addTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        pastBookingsPanel = new javax.swing.JPanel();
        titlePanelMyBookings = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        bookingListPanel = new javax.swing.JPanel();
        listTypeCB = new javax.swing.JComboBox<>();
        hotelDetailsPanel = new javax.swing.JPanel();
        hotelTitlePanel = new javax.swing.JPanel();
        hotelDetailsRatingLabel = new javax.swing.JLabel();
        numReviewsLabel = new javax.swing.JLabel();
        hotelNameLabel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        hotelImageLabel = new javax.swing.JLabel();
        bookingOptionsPanel = new javax.swing.JPanel();
        checkInLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        hotelDetailsOptionsBottomPanel = new javax.swing.JPanel();
        bookNowButton = new javax.swing.JButton();
        checkInConfDatePanel = new custom.components.DatePanel();
        checkOutConfDatePanel = new custom.components.DatePanel();
        bookingConfirmationLinkLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        descriptionPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        descriptionLabelContainerPanel = new javax.swing.JPanel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        amenitiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amenitiesTAScrollPane = new javax.swing.JScrollPane();
        amenitiesTA = new javax.swing.JTextArea();
        backPanel = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();

        changePasswordDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        changePasswordDialog.setBackground(new java.awt.Color(204, 204, 204));
        changePasswordDialog.setMinimumSize(new java.awt.Dimension(638, 361));

        changePasswordOkButton.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        changePasswordOkButton.setText("OK");
        changePasswordOkButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        changePasswordOkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordOkButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel2.setText("Old Password");

        jLabel3.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel3.setText("New Password");

        jLabel4.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel4.setText("Confirm New Password");

        oldPasswordPF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N

        confirmNewPasswordPF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N

        newPasswordPF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N

        javax.swing.GroupLayout changePasswordDialogLayout = new javax.swing.GroupLayout(changePasswordDialog.getContentPane());
        changePasswordDialog.getContentPane().setLayout(changePasswordDialogLayout);
        changePasswordDialogLayout.setHorizontalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changePasswordDialogLayout.createSequentialGroup()
                        .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(67, 67, 67)
                        .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oldPasswordPF)
                            .addComponent(newPasswordPF)
                            .addComponent(confirmNewPasswordPF, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addGap(92, 92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePasswordDialogLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(changePasswordOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        changePasswordDialogLayout.setVerticalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changePasswordDialogLayout.createSequentialGroup()
                        .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePasswordDialogLayout.createSequentialGroup()
                                .addGroup(changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oldPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newPasswordPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(confirmNewPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(changePasswordOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        modifyDateDialog.setMinimumSize(new java.awt.Dimension(520, 300));
        modifyDateDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        modifyDateDialogPanel1.setMinimumSize(new java.awt.Dimension(447, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        modifyDateDialog.getContentPane().add(modifyDateDialogPanel1, gridBagConstraints);

        changeGuestRoomDialog.setMinimumSize(new java.awt.Dimension(533, 173));
        changeGuestRoomDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        guestRoomDialogPanel2.setMinimumSize(new java.awt.Dimension(579, 293));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        changeGuestRoomDialog.getContentPane().add(guestRoomDialogPanel2, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BISTAR HI BISTAR"); // NOI18N
        setBackground(new java.awt.Color(25, 25, 25));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setMinimumSize(new java.awt.Dimension(199, 455));

        body.setBackground(new java.awt.Color(59, 35, 59));

        bookHotelsPanelButton.setBackground(new java.awt.Color(36, 119, 119));
        bookHotelsPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookHotelsPanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookHotelsPanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookHotelsPanelButtonMouseExited(evt);
            }
        });

        bookHotelsLabel.setBackground(new java.awt.Color(36, 119, 119));
        bookHotelsLabel.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        bookHotelsLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookHotelsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bookHotelsLabel.setText("Book Hotels  ");
        bookHotelsLabel.setFocusable(false);

        javax.swing.GroupLayout bookHotelsPanelButtonLayout = new javax.swing.GroupLayout(bookHotelsPanelButton);
        bookHotelsPanelButton.setLayout(bookHotelsPanelButtonLayout);
        bookHotelsPanelButtonLayout.setHorizontalGroup(
            bookHotelsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookHotelsPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookHotelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookHotelsPanelButtonLayout.setVerticalGroup(
            bookHotelsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookHotelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        myBookingsPanelButton.setBackground(new java.awt.Color(59, 35, 59));
        myBookingsPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myBookingsPanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myBookingsPanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myBookingsPanelButtonMouseExited(evt);
            }
        });

        myBookingsLabel.setBackground(new java.awt.Color(51, 30, 51));
        myBookingsLabel.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        myBookingsLabel.setForeground(new java.awt.Color(191, 191, 191));
        myBookingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myBookingsLabel.setText("My Bookings  ");

        javax.swing.GroupLayout myBookingsPanelButtonLayout = new javax.swing.GroupLayout(myBookingsPanelButton);
        myBookingsPanelButton.setLayout(myBookingsPanelButtonLayout);
        myBookingsPanelButtonLayout.setHorizontalGroup(
            myBookingsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myBookingsPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myBookingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myBookingsPanelButtonLayout.setVerticalGroup(
            myBookingsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myBookingsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        settingsPanelButton.setBackground(new java.awt.Color(59, 35, 59));
        settingsPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsPanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsPanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsPanelButtonMouseExited(evt);
            }
        });

        myProfileLabel.setBackground(new java.awt.Color(59, 35, 59));
        myProfileLabel.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        myProfileLabel.setForeground(new java.awt.Color(191, 191, 191));
        myProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myProfileLabel.setText("My Profile");
        myProfileLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout settingsPanelButtonLayout = new javax.swing.GroupLayout(settingsPanelButton);
        settingsPanelButton.setLayout(settingsPanelButtonLayout);
        settingsPanelButtonLayout.setHorizontalGroup(
            settingsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsPanelButtonLayout.setVerticalGroup(
            settingsPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myProfileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        welcomeLabel.setBackground(new java.awt.Color(59, 35, 59));
        welcomeLabel.setFont(new java.awt.Font("Lato Black", 0, 25)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(249, 249, 249));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText(" Welcome Susila! ");
        welcomeLabel.setOpaque(true);

        logoutLinkLabel.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        logoutLinkLabel.setForeground(new java.awt.Color(191, 191, 191));
        logoutLinkLabel.setText("Logout");
        logoutLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLinkLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsPanelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myBookingsPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookHotelsPanelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookHotelsPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myBookingsPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addComponent(logoutLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.5;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(sidebar, gridBagConstraints);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(921, 608));
        mainPanel.setName(""); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        bookPanel.setBackground(new java.awt.Color(25, 25, 25));

        jLabel9.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Location");

        jLabel10.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");

        priceSlider.setBackground(new java.awt.Color(25, 25, 25));
        priceSlider.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        priceSlider.setMaximum(20000);
        priceSlider.setValue(3000);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        locationComboBox.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gondwa", "Thane", "Awadh" }));
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });

        roomPanel.setBackground(new java.awt.Color(25, 25, 25));
        roomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Hotels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Black", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        roomPanel.setLayout(new java.awt.GridBagLayout());

        roomScrollPane.setBackground(new java.awt.Color(25, 25, 25));
        roomScrollPane.setBorder(null);
        roomScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        roomListPanel.setBackground(new java.awt.Color(25, 25, 25));
        roomListPanel.setLayout(new java.awt.GridBagLayout());
        roomScrollPane.setViewportView(roomListPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        roomPanel.add(roomScrollPane, gridBagConstraints);

        goButton.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        titlePanelBook.setBackground(new java.awt.Color(25, 25, 25));
        titlePanelBook.setLayout(new java.awt.GridBagLayout());

        priceSpinner.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(3000.0d, null, 20000.0d, 250.0d));
        priceSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSpinnerStateChanged(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Book Your Hotel");

        jLabel19.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Check In");

        jLabel20.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Check Out");

        checkInDatePanel.setBackground(new java.awt.Color(25, 25, 25));

        checkOutDatePanel.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePanelBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(checkInDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(checkOutDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(75, 75, 75)
                                .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(322, 469, Short.MAX_VALUE))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addComponent(guestRoomPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(goButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21)
                        .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(titlePanelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(priceSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goButton)
                    .addComponent(guestRoomPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20))
                    .addComponent(checkInDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(bookPanel, "bookPanel");

        myProfilePanel.setBackground(new java.awt.Color(25, 25, 25));

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");

        jLabel7.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pincode");

        editButton.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        fNameTF.setEditable(false);
        fNameTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        fNameTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fNameTF.setEnabled(false);

        emailTF.setEditable(false);
        emailTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        emailTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        emailTF.setEnabled(false);
        emailTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTFFocusGained(evt);
            }
        });

        titlePanelSettings.setBackground(new java.awt.Color(25, 25, 25));
        titlePanelSettings.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("My Profile");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        titlePanelSettings.add(jLabel14, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email Address");

        jLabel11.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Residential Add.");

        mobileTF.setEditable(false);
        mobileTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        mobileTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        mobileTF.setEnabled(false);
        mobileTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileTFFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile Number");

        pinCodeTF.setEditable(false);
        pinCodeTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        pinCodeTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        pinCodeTF.setEnabled(false);
        pinCodeTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pinCodeTFFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DOB");

        dobTF.setEditable(false);
        dobTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        dobTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        dobTF.setEnabled(false);

        addTF.setEditable(false);
        addTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        addTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        addTF.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Last Name");

        lNameTF.setEditable(false);
        lNameTF.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        lNameTF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        lNameTF.setEnabled(false);

        javax.swing.GroupLayout myProfilePanelLayout = new javax.swing.GroupLayout(myProfilePanel);
        myProfilePanel.setLayout(myProfilePanelLayout);
        myProfilePanelLayout.setHorizontalGroup(
            myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(myProfilePanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfilePanelLayout.createSequentialGroup()
                        .addComponent(editButton)
                        .addGap(60, 60, 60)
                        .addComponent(changePasswordButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myProfilePanelLayout.createSequentialGroup()
                        .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(44, 44, 44)
                        .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNameTF)
                            .addComponent(emailTF)
                            .addComponent(mobileTF)
                            .addComponent(pinCodeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                            .addComponent(addTF, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                            .addComponent(fNameTF, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50))))
        );
        myProfilePanelLayout.setVerticalGroup(
            myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfilePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titlePanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myProfilePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myProfilePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(changePasswordButton))
                .addGap(74, 74, 74))
        );

        mainPanel.add(myProfilePanel, "settingsPanel");

        pastBookingsPanel.setBackground(new java.awt.Color(25, 25, 25));
        pastBookingsPanel.setLayout(new java.awt.GridBagLayout());

        titlePanelMyBookings.setBackground(new java.awt.Color(25, 25, 25));
        titlePanelMyBookings.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Our Past Collaborations :)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        titlePanelMyBookings.add(jLabel15, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pastBookingsPanel.add(titlePanelMyBookings, gridBagConstraints);

        bookingListPanel.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout bookingListPanelLayout = new javax.swing.GroupLayout(bookingListPanel);
        bookingListPanel.setLayout(bookingListPanelLayout);
        bookingListPanelLayout.setHorizontalGroup(
            bookingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bookingListPanelLayout.setVerticalGroup(
            bookingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 14.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pastBookingsPanel.add(bookingListPanel, gridBagConstraints);

        listTypeCB.setFont(new java.awt.Font("Lato Black", 0, 30)); // NOI18N
        listTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confirmed Bookings", "Waiting List", "Previous Bookings" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 19, 19, 19);
        pastBookingsPanel.add(listTypeCB, gridBagConstraints);

        mainPanel.add(pastBookingsPanel, "pastBookingsPanel");

        hotelDetailsPanel.setBackground(new java.awt.Color(25, 25, 25));
        hotelDetailsPanel.setLayout(new java.awt.GridBagLayout());

        hotelTitlePanel.setBackground(new java.awt.Color(25, 25, 25));

        hotelDetailsRatingLabel.setFont(new java.awt.Font("FreeMono", 0, 36)); // NOI18N
        hotelDetailsRatingLabel.setForeground(new java.awt.Color(255, 255, 0));
        hotelDetailsRatingLabel.setText("Rating");

        numReviewsLabel.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        numReviewsLabel.setForeground(new java.awt.Color(255, 255, 255));
        numReviewsLabel.setText("3,454 reviews");

        hotelNameLabel.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        hotelNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        hotelNameLabel.setText("RESHMA HOTEL");

        javax.swing.GroupLayout hotelTitlePanelLayout = new javax.swing.GroupLayout(hotelTitlePanel);
        hotelTitlePanel.setLayout(hotelTitlePanelLayout);
        hotelTitlePanelLayout.setHorizontalGroup(
            hotelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelTitlePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(hotelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hotelTitlePanelLayout.createSequentialGroup()
                        .addComponent(hotelDetailsRatingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numReviewsLabel))
                    .addComponent(hotelNameLabel))
                .addContainerGap(1015, Short.MAX_VALUE))
        );
        hotelTitlePanelLayout.setVerticalGroup(
            hotelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelTitlePanelLayout.createSequentialGroup()
                .addComponent(hotelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hotelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelDetailsRatingLabel)
                    .addComponent(numReviewsLabel)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.5;
        hotelDetailsPanel.add(hotelTitlePanel, gridBagConstraints);

        imagePanel.setBackground(new java.awt.Color(25, 25, 25));
        imagePanel.setLayout(new java.awt.GridBagLayout());

        hotelImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel.jpg"))); // NOI18N
        hotelImageLabel.setText("\n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        imagePanel.add(hotelImageLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 3.0;
        hotelDetailsPanel.add(imagePanel, gridBagConstraints);

        bookingOptionsPanel.setBackground(new java.awt.Color(25, 25, 25));
        bookingOptionsPanel.setLayout(new java.awt.GridBagLayout());

        checkInLabel.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        checkInLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkInLabel.setText("Check In:");
        checkInLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        checkInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 30, 3, 3);
        bookingOptionsPanel.add(checkInLabel, gridBagConstraints);

        totalPriceLabel.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(0, 198, 0));
        totalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPriceLabel.setText("Rs. 34,981");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        bookingOptionsPanel.add(totalPriceLabel, gridBagConstraints);

        hotelDetailsOptionsBottomPanel.setBackground(new java.awt.Color(25, 25, 25));
        hotelDetailsOptionsBottomPanel.setLayout(new java.awt.GridBagLayout());

        bookNowButton.setBackground(new java.awt.Color(59, 35, 59));
        bookNowButton.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        bookNowButton.setForeground(new java.awt.Color(255, 255, 255));
        bookNowButton.setText("BOOK NOW");
        bookNowButton.setContentAreaFilled(false);
        bookNowButton.setOpaque(true);
        bookNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNowButtonActionPerformed(evt);
            }
        });
        hotelDetailsOptionsBottomPanel.add(bookNowButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        bookingOptionsPanel.add(hotelDetailsOptionsBottomPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        bookingOptionsPanel.add(checkInConfDatePanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        bookingOptionsPanel.add(checkOutConfDatePanel, gridBagConstraints);

        bookingConfirmationLinkLabel.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        bookingConfirmationLinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookingConfirmationLinkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingConfirmationLinkLabel.setText("3 Executive Rooms, 18 Guests");
        bookingConfirmationLinkLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bookingConfirmationLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookingConfirmationLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingConfirmationLinkLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        bookingOptionsPanel.add(bookingConfirmationLinkLabel, gridBagConstraints);

        checkOutLabel.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        checkOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkOutLabel.setText("Check Out:");
        checkOutLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        checkOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 30, 3, 3);
        bookingOptionsPanel.add(checkOutLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 3.0;
        hotelDetailsPanel.add(bookingOptionsPanel, gridBagConstraints);

        descriptionPanel.setBackground(new java.awt.Color(25, 25, 25));
        descriptionPanel.setLayout(new java.awt.GridBagLayout());

        headingLabel.setFont(new java.awt.Font("Lato Black", 0, 36)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("About");
        headingLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        headingLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(59, 35, 59)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        descriptionPanel.add(headingLabel, gridBagConstraints);

        descriptionLabelContainerPanel.setBackground(new java.awt.Color(25, 25, 25));
        descriptionLabelContainerPanel.setLayout(new java.awt.GridBagLayout());

        descriptionScrollPane.setBackground(new java.awt.Color(25, 25, 25));
        descriptionScrollPane.setBorder(null);
        descriptionScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(25, 25, 25));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        descriptionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setTabSize(4);
        descriptionTextArea.setText("The InterContinental Mauritius Resort Balaclava Fort is located on one of the most pristine stretches of beach overlooking Balaclava, Mauritius. Offering 210 well-appointed rooms including 10 presidential suites, 40 family-type, 20 Jacuzzi rooms and 140 Deluxe rooms. Facilities include: 3 bars, 5 restaurants, 2 swimming pools ( all heated in winter ), 8 massage rooms, a unique private island, Planet Trekkers kids club, recreational activities, tennis court, 4 meeting rooms & 1 ballroom.");
        descriptionTextArea.setWrapStyleWord(true);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        descriptionLabelContainerPanel.add(descriptionScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        descriptionPanel.add(descriptionLabelContainerPanel, gridBagConstraints);

        amenitiesPanel.setBackground(new java.awt.Color(25, 25, 25));
        amenitiesPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 188, 188));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amenities");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        amenitiesPanel.add(jLabel1, gridBagConstraints);

        amenitiesTAScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        amenitiesTA.setEditable(false);
        amenitiesTA.setBackground(new java.awt.Color(25, 25, 25));
        amenitiesTA.setColumns(20);
        amenitiesTA.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        amenitiesTA.setForeground(new java.awt.Color(188, 188, 188));
        amenitiesTA.setLineWrap(true);
        amenitiesTA.setRows(5);
        amenitiesTA.setText("Business Centre with Internet Access\nFitness Centre with Gym / Workout Room\nFree High Speed Internet (WiFi)\nChildren Activities (Kid / Family Friendly)\nWheelchair Access\nSpa\nPool\nRoom Service");
        amenitiesTA.setWrapStyleWord(true);
        amenitiesTAScrollPane.setViewportView(amenitiesTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        amenitiesPanel.add(amenitiesTAScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        descriptionPanel.add(amenitiesPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 0, 0);
        hotelDetailsPanel.add(descriptionPanel, gridBagConstraints);

        backPanel.setBackground(new java.awt.Color(25, 25, 25));

        backLabel.setBackground(new java.awt.Color(25, 25, 25));
        backLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setText("\\u2190");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addComponent(backLabel)
                .addGap(0, 1288, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backLabel))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 0.5;
        hotelDetailsPanel.add(backPanel, gridBagConstraints);

        mainPanel.add(hotelDetailsPanel, "hotelDetailsPanel");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 7.5;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelButtonMouseClicked
        // TODO add your handling code here:

        personalize();
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "settingsPanel");
        resetBgColor();
        UIMethods.setSelectedPanelButton(settingsPanelButton, myProfileLabel);
        isSelected[2] = true;

    }//GEN-LAST:event_settingsPanelButtonMouseClicked

    private void myBookingsPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBookingsPanelButtonMouseClicked
        // TODO add your handling code here:
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "pastBookingsPanel");
        resetBgColor();
        UIMethods.setSelectedPanelButton(myBookingsPanelButton, myBookingsLabel);
        isSelected[1] = true;
    }//GEN-LAST:event_myBookingsPanelButtonMouseClicked

    private void bookHotelsPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookHotelsPanelButtonMouseClicked
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "bookPanel");
        resetBgColor();
        UIMethods.setSelectedPanelButton(bookHotelsPanelButton, bookHotelsLabel);
        isSelected[0] = true;

    }//GEN-LAST:event_bookHotelsPanelButtonMouseClicked

    private void bookHotelsPanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookHotelsPanelButtonMouseEntered
        // TODO add your handling code here:
        if (!isSelected[0]) {
            UIMethods.setHoveredPanelButton(bookHotelsPanelButton, true);
        }
    }//GEN-LAST:event_bookHotelsPanelButtonMouseEntered

    private void myBookingsPanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBookingsPanelButtonMouseEntered
        if (!isSelected[1]) {
            UIMethods.setHoveredPanelButton(myBookingsPanelButton, true);
        }
    }//GEN-LAST:event_myBookingsPanelButtonMouseEntered

    private void settingsPanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelButtonMouseEntered
        if (!isSelected[2]) {
            UIMethods.setHoveredPanelButton(settingsPanelButton, true);
        }
    }//GEN-LAST:event_settingsPanelButtonMouseEntered

    private void bookHotelsPanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookHotelsPanelButtonMouseExited
        if (!isSelected[0]) {
            UIMethods.setHoveredPanelButton(bookHotelsPanelButton, false);
        }
    }//GEN-LAST:event_bookHotelsPanelButtonMouseExited

    private void myBookingsPanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBookingsPanelButtonMouseExited
        if (!isSelected[1]) {
            UIMethods.setHoveredPanelButton(myBookingsPanelButton, false);
        }
    }//GEN-LAST:event_myBookingsPanelButtonMouseExited

    private void settingsPanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelButtonMouseExited
        if (!isSelected[2]) {
            UIMethods.setHoveredPanelButton(settingsPanelButton, false);
        }
    }//GEN-LAST:event_settingsPanelButtonMouseExited

    private void logoutLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkLabelMouseEntered
        logoutLinkLabel.setForeground(pressedButtonFontColor);
    }//GEN-LAST:event_logoutLinkLabelMouseEntered

    private void logoutLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkLabelMouseExited
        logoutLinkLabel.setForeground(defaultButtonFontColor);
    }//GEN-LAST:event_logoutLinkLabelMouseExited

    private void logoutLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkLabelMouseClicked
        logout();
    }//GEN-LAST:event_logoutLinkLabelMouseClicked

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
        priceSpinner.setValue(priceSlider.getValue());

    }//GEN-LAST:event_priceSliderStateChanged

    private void priceSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSpinnerStateChanged
        double d = Double.parseDouble(priceSpinner.getValue().toString());
        priceSlider.setValue((int) d);
    }//GEN-LAST:event_priceSpinnerStateChanged

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        //TODO: Get all the relevant details from the given fields and return array of HotelListItemPanel objects

        HotelListItemPanel results[];
        //dummy code starts
        //dummy result array
        String hotelName = "Hotel Reshma";
        String[] roomTypes = {"Reshma Ka", "Savita ka", "Phuljadi ka", "Lalu ka"};
        double[] prices = {3000, 2500, 1500, -200};
        int stars = 3;
        resultList = new HotelListItemPanel[60];
        for (int i = 0; i < 60; i++) {
            resultList[i] = new HotelListItemPanel(new HotelDesc(hotelName, roomTypes, prices, stars, 2345, "Bada sa description", "Wi-Fi"), this, i);
        }

        //dummy code ends
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.FIRST_LINE_START;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 0.3;

        roomListPanel.removeAll();
        roomListPanel.revalidate();
        roomListPanel.repaint();
        for (int i = 0; i < resultList.length; i++) {
            gbc.gridy = i;
            roomListPanel.add(resultList[i], gbc);
        }

        //TODO: see if revalidate() can/should be removed
        roomListPanel.revalidate();
        roomListPanel.repaint();

    }//GEN-LAST:event_goButtonActionPerformed

    private void bookNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNowButtonActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "bookPanel");
    }//GEN-LAST:event_backLabelMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (!isEditing) {
            fNameTF.setEditable(true);
            lNameTF.setEditable(true);
            emailTF.setEditable(true);
            addTF.setEditable(true);
            mobileTF.setEditable(true);
            dobTF.setEditable(true);
            pinCodeTF.setEditable(true);
            fNameTF.setEnabled(true);
            lNameTF.setEnabled(true);
            emailTF.setEnabled(true);
            addTF.setEnabled(true);
            mobileTF.setEnabled(true);
            dobTF.setEnabled(true);
            pinCodeTF.setEnabled(true);
            isEditing = true;
            editButton.setText("Save");

        } else {

            if (saveDetails()) {

                fNameTF.setEditable(false);
                lNameTF.setEditable(false);
                emailTF.setEditable(false);
                addTF.setEditable(false);
                mobileTF.setEditable(false);
                pinCodeTF.setEditable(false);
                dobTF.setEditable(false);
                fNameTF.setEnabled(false);
                lNameTF.setEnabled(false);
                emailTF.setEnabled(false);
                addTF.setEnabled(false);
                dobTF.setEnabled(false);
                mobileTF.setEnabled(false);
                pinCodeTF.setEnabled(false);
                isEditing = false;
                editButton.setText("Edit");

            } else {

                isEditing = true;
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        changePasswordDialog.setLocationRelativeTo(null);
        
        changePasswordDialog.setVisible(true);
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void changePasswordOkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordOkButtonMouseClicked
        
     /*  if(Arrays.equals(oldPasswordTF.getPassword().trim(), user.getPassword()))
        {
            Helper.updatePassword();
        }else */
    }//GEN-LAST:event_changePasswordOkButtonMouseClicked

    private void emailTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTFFocusGained
        
            emailTF.setForeground(Color.BLACK);
            emailTF.setText("");
    }//GEN-LAST:event_emailTFFocusGained

    private void mobileTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileTFFocusGained
        
            mobileTF.setForeground(Color.BLACK);
            mobileTF.setText("");
    }//GEN-LAST:event_mobileTFFocusGained

    private void pinCodeTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinCodeTFFocusGained
        
            pinCodeTF.setForeground(Color.BLACK);
            pinCodeTF.setText("");
    }//GEN-LAST:event_pinCodeTFFocusGained

    private void bookingConfirmationLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingConfirmationLinkLabelMouseClicked
            changeGuestRoomDialog.setLocationRelativeTo(null);
            changeGuestRoomDialog.setVisible(true);
    }//GEN-LAST:event_bookingConfirmationLinkLabelMouseClicked

    private void resetBgColor() {
        //reset bg color of all buttons
        bookHotelsPanelButton.setBackground(defaultButtonColor);
        myBookingsPanelButton.setBackground(defaultButtonColor);
        settingsPanelButton.setBackground(defaultButtonColor);

        //reset font of all labels
        bookHotelsLabel.setFont(defaultButtonFont);
        myBookingsLabel.setFont(defaultButtonFont);
        myProfileLabel.setFont(defaultButtonFont);

        //reset font color of all labels
        bookHotelsLabel.setForeground(defaultButtonFontColor);
        myBookingsLabel.setForeground(defaultButtonFontColor);
        myProfileLabel.setForeground(defaultButtonFontColor);

        for (int i = 0; i < 3; i++) {
            isSelected[i] = false;
        }
    }

    private void startupCode() {
        //Tidying up the UI
        resetBgColor();
        UIMethods.setSelectedPanelButton(bookHotelsPanelButton, bookHotelsLabel);
        isSelected[0] = true;
        
        bookHotelsPanelButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        myBookingsPanelButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        settingsPanelButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        roomScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        backLabel.setText("\u2190");//setting the back button unicode
        
        
        dal = new DialogActionListener(guestRoomDialogPanel2,modifyDateDialogPanel1);
        changePasswordDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        changeGuestRoomDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        modifyDateDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);

        //setting up the date panels
        checkInDatePanel.setMinDate(LocalDate.now());
        checkInDatePanel.setMaxDate(LocalDate.now().plusYears(NUMBER_OF_FUTURE_YEARS));
        
        //Personalizing
        personalize();

    }

    //Custom Variable declarations
    private final Color defaultButtonColor = new Color(59, 35, 59);
    private final Color pressedButtonColor = new Color(36, 119, 119);
    private final Color hoverButtonColor = new Color(45, 27, 45);

    private final Color defaultButtonFontColor = new Color(191, 191, 191);
    private final Color pressedButtonFontColor = new Color(250, 250, 250);

    private final Font defaultButtonFont = new Font("Lato", Font.PLAIN, 24);
    private final Font pressedButtonFont = new Font("Lato Black", Font.PLAIN, 24);

    private final Font defaultKeyFont = new Font("Lato Black", Font.PLAIN, 22);
    private final Font defaultValueFont = new Font("Lato", Font.PLAIN, 22);

    private final Color textColor = new Color(0, 0, 0);
    private final Color bgColor = new Color(255, 255, 255);

    private boolean isSelected[] = new boolean[3];//particularly dirty, will replace with PButton once out of netbeans

    private boolean isEditing = false;//state of the edit button in the settings panel
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addTF;
    private javax.swing.JPanel amenitiesPanel;
    private javax.swing.JTextArea amenitiesTA;
    private javax.swing.JScrollPane amenitiesTAScrollPane;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel body;
    private javax.swing.JLabel bookHotelsLabel;
    private javax.swing.JPanel bookHotelsPanelButton;
    private javax.swing.JButton bookNowButton;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JLabel bookingConfirmationLinkLabel;
    private javax.swing.JPanel bookingListPanel;
    private javax.swing.JPanel bookingOptionsPanel;
    private javax.swing.JDialog changeGuestRoomDialog;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JDialog changePasswordDialog;
    private javax.swing.JButton changePasswordOkButton;
    private custom.components.DatePanel checkInConfDatePanel;
    private custom.components.DatePanel checkInDatePanel;
    private javax.swing.JLabel checkInLabel;
    private custom.components.DatePanel checkOutConfDatePanel;
    private custom.components.DatePanel checkOutDatePanel;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JPasswordField confirmNewPasswordPF;
    private javax.swing.JPanel descriptionLabelContainerPanel;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField dobTF;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JButton goButton;
    private custom.components.GuestRoomDialogPanel guestRoomDialogPanel2;
    private custom.components.GuestRoomPanel guestRoomPanel1;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel hotelDetailsOptionsBottomPanel;
    private javax.swing.JPanel hotelDetailsPanel;
    private javax.swing.JLabel hotelDetailsRatingLabel;
    private javax.swing.JLabel hotelImageLabel;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JPanel hotelTitlePanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JComboBox<String> listTypeCB;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JLabel logoutLinkLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JDialog modifyDateDialog;
    private custom.components.ModifyBookingDialogPanel modifyDateDialogPanel1;
    private javax.swing.JLabel myBookingsLabel;
    private javax.swing.JPanel myBookingsPanelButton;
    private javax.swing.JLabel myProfileLabel;
    private javax.swing.JPanel myProfilePanel;
    private javax.swing.JPasswordField newPasswordPF;
    private javax.swing.JLabel numReviewsLabel;
    private javax.swing.JPasswordField oldPasswordPF;
    private javax.swing.JPanel pastBookingsPanel;
    private javax.swing.JTextField pinCodeTF;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JPanel roomListPanel;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JScrollPane roomScrollPane;
    private javax.swing.JPanel settingsPanelButton;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanelBook;
    private javax.swing.JPanel titlePanelMyBookings;
    private javax.swing.JPanel titlePanelSettings;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private void logout() {
        //TODO: security?
        loginScreen.setVisible(true);
        loginScreen.setEnabled(true);
        this.dispose();
    }

    private void personalize() {
        welcomeLabel.setText(" Welcome " + user.getUsername() + "! ");
        fNameTF.setText(user.getFName());
        lNameTF.setText(user.getLName());
        emailTF.setText(user.getEmail());
        addTF.setText(user.getAddress());
        mobileTF.setText(user.getMobile());
        pinCodeTF.setText(Integer.toString(user.getPinCode()));
    }

    private boolean saveDetails() {            // Method to change the details of the user in the database

        try {

            if (!Verify.isValidEmail(emailTF.getText().trim())) {

                emailTF.setText("Invalid Email");
                emailTF.setForeground(Color.RED);
                return false;

            } else if (!Verify.isValidPinCode(pinCodeTF.getText().trim())) {

                pinCodeTF.setText("Invalid Pincode");
                pinCodeTF.setForeground(Color.RED);
                return false;

            } else if (!Verify.isValidMobile(mobileTF.getText().trim())) {

                mobileTF.setText("Invalid Mobile Number");
                mobileTF.setForeground(Color.RED);
                return false;

            } else {

                user.setFName(fNameTF.getText().trim());
                user.setLName(lNameTF.getText().trim());
                user.setAddress(addTF.getText().trim());
                user.setEmail(emailTF.getText().trim());
                user.setMobile(mobileTF.getText().trim());
                user.setPinCode(Integer.parseInt(pinCodeTF.getText().trim()));

                Helper.updateUserProfile(user);

                return true;
            }
        } catch (NumberFormatException e) {

            pinCodeTF.setText("Invalid Pincode");
            pinCodeTF.setForeground(Color.RED);
            e.printStackTrace();
            return false;

        } catch (Exception e) {
            
            e.printStackTrace();
            return false;
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        //TODO: Goto the checkout page or review page
        JLabel label = (JLabel) e.getComponent();
        JPanel j = (JPanel) label.getParent();
        HotelListItemPanel i;

        if (j instanceof HotelListItemPanel) {
            i = (HotelListItemPanel) j;
            loadHotel(resultList[i.getIndex()]);
        } else {//IMP! Assuming the type of rooms wont have the character '-' inside them!!
            i = (HotelListItemPanel) j.getParent().getParent();
            String s = label.getText();
            s = s.substring(s.indexOf('>') + 1, s.indexOf('-') - 1);
            System.out.println(s);
            loadHotel(resultList[i.getIndex()], s);
        }
        // loadHotel(resultList[i.getIndex()]);
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "hotelDetailsPanel");
        System.out.println("Clicked On " + ((JLabel) e.getComponent()).getText());

    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {
        JLabel j = (JLabel) e.getComponent();
        if (j.getName().equals("underline")) {
            j.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, j.getForeground()));
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        JLabel j = (JLabel) e.getComponent();
        if (j.getName().equals("underline")) {
            j.setBorder(BorderFactory.createEmptyBorder(0, 0, 1, 0));
        }
        //j.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
    }

    private void loadHotel(HotelListItemPanel hotelListItemPanel) {
        HotelDesc des = hotelListItemPanel.getHotelDesc();
        loadHotel(hotelListItemPanel, des.getRoomTypes()[0]);
    }

    private void loadHotel(HotelListItemPanel hotelListItemPanel, String type) {
        HotelDesc des = hotelListItemPanel.getHotelDesc();
        hotelNameLabel.setText(des.getHotelName());
        numReviewsLabel.setText(des.getNumReviews() + " reviews");//TODO: add commas- as in "3,245" instead of "3245"
        hotelDetailsRatingLabel.setText(UIMethods.getRatingString(des.getStars()));
        bookingConfirmationLinkLabel.setText(numOfRooms + " " + type + ", " + numOfGuest + " Guests");
        totalPriceLabel.setText(des.getCost(type, numOfRooms, checkIn, checkOut) + "");
        descriptionTextArea.setText(des.getDescription());
        amenitiesTA.setText(des.getAmenities());

    }

    
}
