/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import verifyingTools.Verify;
import bridge.Helper;
import internal.User;


/**
 *
 * @author Sarthak
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
        errorPasswordLabel.setVisible(false);
        errorPasswordMatchLabel.setVisible(false);
        errorUsernameLabel.setVisible(false);
        errorPinCodeLabel.setVisible(false);
        errorEmptyField.setVisible(false);
        errorMobileNumberLabel.setVisible(false);
        errorEmailIDLabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        signupSuccessfulDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        outerPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        titlePane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pinCodeTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        centerBottomPanel = new javax.swing.JPanel();
        signUpButton = new javax.swing.JButton();
        confirmPasswordPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        fNameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        datePanel1 = new custom.components.DatePanel();
        jLabel9 = new javax.swing.JLabel();
        errorPasswordMatchLabel = new javax.swing.JLabel();
        errorPinCodeLabel = new javax.swing.JLabel();
        errorPasswordLabel = new javax.swing.JLabel();
        errorUsernameLabel = new javax.swing.JLabel();
        errorEmptyField = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobileNumberTF = new javax.swing.JTextField();
        errorMobileNumberLabel = new javax.swing.JLabel();
        errorEmailIDLabel = new javax.swing.JLabel();

        signupSuccessfulDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        signupSuccessfulDialog.setTitle("Sign Up- BISTAR HI BISTAR");
        signupSuccessfulDialog.setMinimumSize(new java.awt.Dimension(419, 157));
        signupSuccessfulDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sign Up Successful!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        signupSuccessfulDialog.getContentPane().add(jLabel11, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up - BISTAR HI BISTAR");
        setBackground(new java.awt.Color(255, 255, 255));

        outerPanel.setBackground(new java.awt.Color(59, 35, 59));
        outerPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        outerPanel.setLayout(new java.awt.GridBagLayout());

        container.setBackground(new java.awt.Color(204, 204, 204));
        container.setLayout(new java.awt.GridBagLayout());

        titlePane.setBackground(new java.awt.Color(204, 204, 204));
        titlePane.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Lato Black", 0, 56)); // NOI18N
        titleLabel.setText("Sign Up");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        titlePane.add(titleLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        container.add(titlePane, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel2.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel3.setText("DOB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel4, gridBagConstraints);

        usernameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(usernameTF, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel5.setText("Mobile number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel6.setText("Email Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel6, gridBagConstraints);

        pinCodeTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(pinCodeTF, gridBagConstraints);

        addressTextArea.setColumns(5);
        addressTextArea.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(5);
        addressTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(addressTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 254;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        container.add(jScrollPane1, gridBagConstraints);

        centerBottomPanel.setBackground(new java.awt.Color(204, 204, 204));
        centerBottomPanel.setLayout(new java.awt.GridBagLayout());

        signUpButton.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        centerBottomPanel.add(signUpButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        container.add(centerBottomPanel, gridBagConstraints);

        confirmPasswordPF.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(confirmPasswordPF, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel1.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel1, gridBagConstraints);

        lNameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(lNameTF, gridBagConstraints);

        fNameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(fNameTF, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel7.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel7, gridBagConstraints);

        passwordPF.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(passwordPF, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel8.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel8, gridBagConstraints);

        emailTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(emailTF, gridBagConstraints);

        datePanel1.setBackground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(datePanel1, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel9.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel9, gridBagConstraints);

        errorPasswordMatchLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPasswordMatchLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPasswordMatchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPasswordMatchLabel.setText("*Passwords do not match");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        container.add(errorPasswordMatchLabel, gridBagConstraints);

        errorPinCodeLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPinCodeLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPinCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPinCodeLabel.setText("*Invalid pincode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        container.add(errorPinCodeLabel, gridBagConstraints);

        errorPasswordLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPasswordLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPasswordLabel.setText("*Password must be greater than 8 characters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        container.add(errorPasswordLabel, gridBagConstraints);

        errorUsernameLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorUsernameLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorUsernameLabel.setText("*Username already exists");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        container.add(errorUsernameLabel, gridBagConstraints);

        errorEmptyField.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorEmptyField.setForeground(new java.awt.Color(255, 51, 51));
        errorEmptyField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorEmptyField.setText("*All fields are compulsory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        container.add(errorEmptyField, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel10.setText("Pincode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        container.add(jLabel10, gridBagConstraints);

        mobileNumberTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(mobileNumberTF, gridBagConstraints);

        errorMobileNumberLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorMobileNumberLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorMobileNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMobileNumberLabel.setText("*Invalid Mobile Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        container.add(errorMobileNumberLabel, gridBagConstraints);

        errorEmailIDLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorEmailIDLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorEmailIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorEmailIDLabel.setText("*Invalid Email ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        container.add(errorEmailIDLabel, gridBagConstraints);

        scrollPane.setViewportView(container);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 24;
        outerPanel.add(scrollPane, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        //after saving to the database, or canceling, dispose this frame

        errorPasswordLabel.setVisible(false);
        errorPasswordMatchLabel.setVisible(false);
        errorUsernameLabel.setVisible(false);
        errorPinCodeLabel.setVisible(false);
        errorEmptyField.setVisible(false);
        errorMobileNumberLabel.setVisible(false);
        errorEmailIDLabel.setVisible(false);

        User usr = new User();

        try {

            if (fNameTF.getText().length() == 0 || lNameTF.getText().length() == 0 || usernameTF.getText().length() == 0 || addressTextArea.getText().length() == 0 || pinCodeTF.getText().length() == 0 || emailTF.getText().length() == 0 || passwordPF.getPassword().length == 0) {

                errorEmptyField.setVisible(true);

            } else if (!Verify.isValidPassword(passwordPF.getPassword())) {

                errorPasswordLabel.setVisible(true);
                confirmPasswordPF.setText("");
                passwordPF.setText("");

            } else if (!Verify.isValidConfirmPassword(confirmPasswordPF.getPassword(), passwordPF.getPassword())) {

                errorPasswordMatchLabel.setVisible(true);
                confirmPasswordPF.setText("");
                passwordPF.setText("");

            } else if (!Verify.isValidEmail(emailTF.getText().trim())) {

                errorEmailIDLabel.setVisible(true);
                emailTF.setText("");

            } else if (!Verify.isValidPinCode(pinCodeTF.getText().trim())) {

                errorPinCodeLabel.setVisible(true);
                pinCodeTF.setText("");

            } else if (!Verify.isValidMobile(mobileNumberTF.getText().trim())) {

                errorMobileNumberLabel.setVisible(true);
                mobileNumberTF.setText("");

            } else {

                usr.setFName(fNameTF.getText().trim());
                usr.setLName(lNameTF.getText().trim());
                usr.setUsername(usernameTF.getText().trim());
                usr.setAddress(addressTextArea.getText());
                usr.setPinCode(Integer.parseInt(pinCodeTF.getText().trim()));
                usr.setEmail(emailTF.getText().trim());
                usr.setPassword(new String(passwordPF.getPassword()));
                usr.setMobile(mobileNumberTF.getText().trim());

                    if (!Helper.signUp(usr)) {

                        errorUsernameLabel.setVisible(true);  // Method to check and enter user data in database

                    } else {
                        signupSuccessfulDialog.setLocationRelativeTo(null);
                        signupSuccessfulDialog.setVisible(true);
                        this.dispose();

                    }

            }

        } catch (NumberFormatException e) {

            errorPinCodeLabel.setVisible(true);
            pinCodeTF.setText("");
            e.printStackTrace();

        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_signUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JPanel centerBottomPanel;
    private javax.swing.JPasswordField confirmPasswordPF;
    private javax.swing.JPanel container;
    private custom.components.DatePanel datePanel1;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel errorEmailIDLabel;
    private javax.swing.JLabel errorEmptyField;
    private javax.swing.JLabel errorMobileNumberLabel;
    private javax.swing.JLabel errorPasswordLabel;
    private javax.swing.JLabel errorPasswordMatchLabel;
    private javax.swing.JLabel errorPinCodeLabel;
    private javax.swing.JLabel errorUsernameLabel;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JTextField mobileNumberTF;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JTextField pinCodeTF;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton signUpButton;
    private javax.swing.JDialog signupSuccessfulDialog;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePane;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
