/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import verifyingTools.Verify;
import bridge.Helper;
import internal.User;
import java.time.LocalDate;


/**
 *
 * @author Sarthak
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
        errorPasswordLabel.setVisible(false);
        errorPasswordMatchLabel.setVisible(false);
        errorUsernameLabel.setVisible(false);
        errorPinCodeLabel.setVisible(false);
        errorEmptyField.setVisible(false);
        errorMobileNumberLabel.setVisible(false);
        errorEmailIDLabel.setVisible(false);
        
        //setting min max date in DatePanel
        datePanel1.setMinDate(LocalDate.of(1900, 1, 1));
        datePanel1.setMaxDate(LocalDate.now());
        datePanel1.setDate(LocalDate.now());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        signupSuccessfulDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        outerPanel = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        titlePane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pinCodeTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        centerBottomPanel = new javax.swing.JPanel();
        confirmPasswordPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        fNameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        datePanel1 = new custom.components.DatePanel();
        jLabel9 = new javax.swing.JLabel();
        errorPasswordMatchLabel = new javax.swing.JLabel();
        errorPinCodeLabel = new javax.swing.JLabel();
        errorPasswordLabel = new javax.swing.JLabel();
        errorUsernameLabel = new javax.swing.JLabel();
        errorEmptyField = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobileNumberTF = new javax.swing.JTextField();
        errorMobileNumberLabel = new javax.swing.JLabel();
        errorEmailIDLabel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();

        signupSuccessfulDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        signupSuccessfulDialog.setTitle("Sign Up- BISTAR HI BISTAR");
        signupSuccessfulDialog.setMinimumSize(new java.awt.Dimension(419, 157));
        signupSuccessfulDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sign Up Successful!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        signupSuccessfulDialog.getContentPane().add(jLabel11, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up - EzyBook");
        setBackground(new java.awt.Color(255, 255, 255));

        outerPanel.setBackground(new java.awt.Color(59, 35, 59));
        outerPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        outerPanel.setLayout(new java.awt.GridBagLayout());

        container.setBackground(new java.awt.Color(204, 204, 204));

        titlePane.setBackground(new java.awt.Color(204, 204, 204));
        titlePane.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Lato Black", 0, 56)); // NOI18N
        titleLabel.setText("Sign Up");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        titlePane.add(titleLabel, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel3.setText("DOB");

        jLabel4.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel4.setText("Password");

        usernameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        usernameTF.setNextFocusableComponent(datePanel1);

        jLabel5.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel5.setText("Mobile number");

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel6.setText("Email Address");

        pinCodeTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        pinCodeTF.setNextFocusableComponent(mobileNumberTF);

        addressTextArea.setColumns(5);
        addressTextArea.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(5);
        addressTextArea.setWrapStyleWord(true);
        addressTextArea.setNextFocusableComponent(pinCodeTF);
        jScrollPane1.setViewportView(addressTextArea);

        centerBottomPanel.setBackground(new java.awt.Color(204, 204, 204));
        centerBottomPanel.setLayout(new java.awt.GridBagLayout());

        confirmPasswordPF.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        confirmPasswordPF.setNextFocusableComponent(emailTF);

        jLabel1.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel1.setText("Last Name");

        lNameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lNameTF.setNextFocusableComponent(usernameTF);

        fNameTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        fNameTF.setMinimumSize(new java.awt.Dimension(6, 35));
        fNameTF.setNextFocusableComponent(lNameTF);
        fNameTF.setPreferredSize(new java.awt.Dimension(6, 35));

        jLabel7.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel7.setText("Confirm Password");

        passwordPF.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        passwordPF.setNextFocusableComponent(confirmPasswordPF);

        jLabel8.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel8.setText("Address");

        emailTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        emailTF.setNextFocusableComponent(addressTextArea);

        datePanel1.setBackground(new java.awt.Color(204, 204, 204));
        datePanel1.setNextFocusableComponent(passwordPF);

        jLabel9.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel9.setText("Username");

        errorPasswordMatchLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPasswordMatchLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPasswordMatchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPasswordMatchLabel.setText("*Passwords do not match");

        errorPinCodeLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPinCodeLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPinCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPinCodeLabel.setText("*Invalid pincode");

        errorPasswordLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorPasswordLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPasswordLabel.setText("*Password must be greater than 8 characters");

        errorUsernameLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorUsernameLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorUsernameLabel.setText("*Username already exists");

        errorEmptyField.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorEmptyField.setForeground(new java.awt.Color(255, 51, 51));
        errorEmptyField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorEmptyField.setText("*All fields are compulsory");

        jLabel10.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel10.setText("Pincode");

        mobileNumberTF.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        mobileNumberTF.setNextFocusableComponent(signUpButton);

        errorMobileNumberLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorMobileNumberLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorMobileNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMobileNumberLabel.setText("*Invalid Mobile Number");

        errorEmailIDLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        errorEmailIDLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorEmailIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorEmailIDLabel.setText("*Invalid Email ID");

        signUpButton.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(264, 264, 264)
                        .addComponent(datePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(errorUsernameLabel))
                    .addComponent(errorMobileNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorEmptyField, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorEmailIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centerBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(47, 47, 47)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pinCodeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(emailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(confirmPasswordPF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(passwordPF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(81, 81, 81)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorPinCodeLabel))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(128, 128, 128))
                        .addGroup(containerLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(132, 132, 132)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(137, 137, 137)))
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(fNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(usernameTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signUpButton)
                .addGap(264, 264, 264))
            .addComponent(errorPasswordMatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(datePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(confirmPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(pinCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(mobileNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPasswordLabel)
                    .addComponent(errorUsernameLabel)
                    .addComponent(errorMobileNumberLabel)
                    .addComponent(errorEmptyField)
                    .addComponent(errorPinCodeLabel)
                    .addComponent(errorPasswordMatchLabel)
                    .addComponent(errorEmailIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(centerBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outerPanel.add(container, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        //after saving to the database, or canceling, dispose this frame

        errorPasswordLabel.setVisible(false);
        errorPasswordMatchLabel.setVisible(false);
        errorUsernameLabel.setVisible(false);
        errorPinCodeLabel.setVisible(false);
        errorEmptyField.setVisible(false);
        errorMobileNumberLabel.setVisible(false);
        errorEmailIDLabel.setVisible(false);

        User usr = new User();

        try {

            if (fNameTF.getText().length() == 0 || lNameTF.getText().length() == 0 || usernameTF.getText().length() == 0 || addressTextArea.getText().length() == 0 || pinCodeTF.getText().length() == 0 || emailTF.getText().length() == 0 || passwordPF.getPassword().length == 0) {

                errorEmptyField.setVisible(true);

            } else if (!Verify.isValidPassword(passwordPF.getPassword())) {

                errorPasswordLabel.setVisible(true);
                confirmPasswordPF.setText("");
                passwordPF.setText("");

            } else if (!Verify.isValidConfirmPassword(confirmPasswordPF.getPassword(), passwordPF.getPassword())) {

                errorPasswordMatchLabel.setVisible(true);
                confirmPasswordPF.setText("");
                passwordPF.setText("");

            } else if (!Verify.isValidEmail(emailTF.getText().trim())) {

                errorEmailIDLabel.setVisible(true);
                emailTF.setText("");

            } else if (!Verify.isValidPinCode(pinCodeTF.getText().trim())) {

                errorPinCodeLabel.setVisible(true);
                pinCodeTF.setText("");

            } else if (!Verify.isValidMobile(mobileNumberTF.getText().trim())) {

                errorMobileNumberLabel.setVisible(true);
                mobileNumberTF.setText("");

            } else {

                usr.setFName(fNameTF.getText().trim());
                usr.setLName(lNameTF.getText().trim());
                usr.setUsername(usernameTF.getText().trim());
                usr.setAddress(addressTextArea.getText());
                usr.setPinCode(Integer.parseInt(pinCodeTF.getText().trim()));
                usr.setEmail(emailTF.getText().trim());
                usr.setPassword(new String(passwordPF.getPassword()));
                usr.setMobile(mobileNumberTF.getText().trim());
                usr.setDOB(datePanel1.getDate());

                    if (!Helper.signUp(usr)) {

                        errorUsernameLabel.setVisible(true);  // Method to check and enter user data in database

                    } else {
                        signupSuccessfulDialog.setLocationRelativeTo(null);
                        signupSuccessfulDialog.setVisible(true);
                        this.dispose();

                    }

            }

        } catch (NumberFormatException e) {

            errorPinCodeLabel.setVisible(true);
            pinCodeTF.setText("");
            e.printStackTrace();

        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_signUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JPanel centerBottomPanel;
    private javax.swing.JPasswordField confirmPasswordPF;
    private javax.swing.JPanel container;
    private custom.components.DatePanel datePanel1;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel errorEmailIDLabel;
    private javax.swing.JLabel errorEmptyField;
    private javax.swing.JLabel errorMobileNumberLabel;
    private javax.swing.JLabel errorPasswordLabel;
    private javax.swing.JLabel errorPasswordMatchLabel;
    private javax.swing.JLabel errorPinCodeLabel;
    private javax.swing.JLabel errorUsernameLabel;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JTextField mobileNumberTF;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JTextField pinCodeTF;
    private javax.swing.JButton signUpButton;
    private javax.swing.JDialog signupSuccessfulDialog;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePane;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
