/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package custom.components;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Sarthak
 */
public class GuestRoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestRoomPanel
     */
    
    private int minRooms =1;
    public final int GUESTS_PER_ROOM=3;
    
    public GuestRoomPanel() {
        initComponents();
        roomSpinner.getModel().addChangeListener((ChangeEvent e) -> {
            if(getRooms()<minRooms){
                setRooms(minRooms);
            }
                
        });
        guestSpinner.getModel().addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                minRooms=((getGuests()%GUESTS_PER_ROOM)==0)?(getGuests()/GUESTS_PER_ROOM):(getGuests()/GUESTS_PER_ROOM+1);
                if(getRooms()<(double)getGuests()/GUESTS_PER_ROOM){                       
                        setRooms(minRooms);
                }
            }
        });
        
    }

    public int getRooms(){
        return (Integer)(roomSpinner.getValue());
    }
    
    public int getGuests(){
        return (Integer)(guestSpinner.getValue());
    }
    public void setRooms(int i){
        roomSpinner.setValue(i);
        
    }
    
    public void setGuests(int i){
        guestSpinner.setValue(i);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        guestPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        guestSpinner = new javax.swing.JSpinner();
        roomPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        roomSpinner = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(25, 25, 25));
        setLayout(new java.awt.GridBagLayout());

        guestPanel.setBackground(new java.awt.Color(25, 25, 25));
        guestPanel.setMinimumSize(new java.awt.Dimension(260, 38));
        guestPanel.setPreferredSize(new java.awt.Dimension(260, 38));
        guestPanel.setLayout(new java.awt.GridBagLayout());

        jLabel17.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Number of Guests");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        guestPanel.add(jLabel17, gridBagConstraints);

        guestSpinner.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        guestSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        guestPanel.add(guestSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(guestPanel, gridBagConstraints);

        roomPanel.setBackground(new java.awt.Color(25, 25, 25));
        roomPanel.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("Lato Black", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Number of Rooms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        roomPanel.add(jLabel16, gridBagConstraints);

        roomSpinner.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        roomSpinner.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        roomPanel.add(roomSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roomPanel, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("(3 guests per room)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(jLabel18, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel guestPanel;
    private javax.swing.JSpinner guestSpinner;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JSpinner roomSpinner;
    // End of variables declaration//GEN-END:variables
}
