/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package custom.components;

/**
 *
 * @author Sarthak
 */
public class ModifyDateDialogPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestRoomDialogPanel
     */
    public ModifyDateDialogPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        changeGuestRoomButton = new javax.swing.JButton();
        changeGuestRoomButton1 = new javax.swing.JButton();
        datePanel1 = new custom.components.DatePanel();
        datePanel2 = new custom.components.DatePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(25, 25, 25));
        setLayout(new java.awt.GridBagLayout());

        changeGuestRoomButton.setBackground(new java.awt.Color(59, 35, 59));
        changeGuestRoomButton.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        changeGuestRoomButton.setForeground(new java.awt.Color(255, 255, 255));
        changeGuestRoomButton.setText("Cancel");
        changeGuestRoomButton.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 13, 13);
        add(changeGuestRoomButton, gridBagConstraints);

        changeGuestRoomButton1.setBackground(new java.awt.Color(59, 35, 59));
        changeGuestRoomButton1.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        changeGuestRoomButton1.setForeground(new java.awt.Color(255, 255, 255));
        changeGuestRoomButton1.setText("Update");
        changeGuestRoomButton1.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 13, 13, 3);
        add(changeGuestRoomButton1, gridBagConstraints);

        datePanel1.setBackground(new java.awt.Color(25, 25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 3, 13);
        add(datePanel1, gridBagConstraints);

        datePanel2.setBackground(new java.awt.Color(25, 25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 3, 13);
        add(datePanel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check In:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 3, 3);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Check Out:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 13, 3, 3);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeGuestRoomButton;
    private javax.swing.JButton changeGuestRoomButton1;
    private custom.components.DatePanel datePanel1;
    private custom.components.DatePanel datePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
