/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package custom.components;

import UI.UIMethods;
import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author Sarthak
 */
public class RatingPanel extends javax.swing.JPanel implements MouseListener {
    JLabel starLabel[] = new JLabel[5];
    boolean emptyState=true;
    static final Color EMPTY_STATE_COLOR = new Color(242, 242, 96);
    static final Color NORMAL_STATE_COLOR = new Color(255,255,0);
    /**
     * Creates new form giveRatingPanel
     */
    public RatingPanel() {
        initComponents();
        setup();
        
        
    }
    
    
    private void setup(){
        GridBagConstraints gbc= new java.awt.GridBagConstraints();
        
        for(int i=0;i<5;i++){
            starLabel[i] = new JLabel();
            starLabel[i].setFont(new java.awt.Font("FreeMono", 0, 48)); // NOI18N
            starLabel[i].setForeground(EMPTY_STATE_COLOR);
            starLabel[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            starLabel[i].setText(UIMethods.getEmptyStarString());
            starLabel[i].addMouseListener(this);
            gbc.fill = java.awt.GridBagConstraints.BOTH;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            add(starLabel[i], gbc);      
        }
    }
    
    private void refreshRating(){
        for(JLabel star: starLabel){
            star.setText(UIMethods.getEmptyStarString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(25, 25, 25));
        setForeground(new java.awt.Color(242, 242, 96));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseClicked(MouseEvent e) {
        if(emptyState){
            emptyState=false;
            for(JLabel star: starLabel){
            star.setForeground(NORMAL_STATE_COLOR);
            }
        }
        
        refreshRating();
        int i=0;
        do{
            starLabel[i].setText(UIMethods.getStarString());
        }while(!starLabel[i++].equals(e.getComponent()) && i<5);//NOTE: Point of contention
        
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        if(emptyState){
            refreshRating();
            int i=0;
            do{
                starLabel[i].setText(UIMethods.getStarString());
            }while(!starLabel[i++].equals(e.getComponent()) && i<5);//NOTE: Point of contention
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
